#pragma once
#include <iostream>
#include <random>
#include <cmath>
#include <ctime>
#include <vector>
#include <unordered_map>
#include <bitset>
#include <string>
#include <sstream>
#include <fstream>
#include "SDL.h"
#include "SDL_image.h"
#include "SDL_ttf.h"